Repository AIN-T/tiggle-frontend, pull requests merged in 2024-11, with the labels that each got.

#7 [Feat] 프로그램 좋아요 기능 구현 [#1]
  package.json
  src/components/reservation/DetailViewComponent.vue
  src/main.js
  src/stores/useProgramsStore.js
Labels: 💛 feature, 🩵 frontend

#8 [Feat] 나의 좋아요 목록 조회 기능 구현 [#2]
  src/components/mypage/MyPageComponent.vue
  src/stores/useProgramsStore.js
Labels: 💛 feature, 🩵 frontend

#9 [Refactor] 좌석 선택 팝업창 수정 및 상세페이지 수정 [#3]
  src/components/book/SeatComponent.vue
  src/components/book/SelectExchangeSeatComponent.vue
  src/components/book/SelectSeatComponent.vue
  src/components/reservation/DetailViewComponent.vue
  src/stores/useBookingStore.js
  src/stores/useProgramsStore.js
Labels: bug, 💛 feature, 🩵 frontend, 💜 refactor

#10 [Feat] 검색 페이지 구현 [#6]
  src/components/common/HeaderComponent.vue
  src/components/main/SearchComponent.vue
  src/pages/SearchPage.vue
  src/router/index.js
  src/stores/useProgramsStore.js
Labels: 💛 feature, 🩵 frontend

#11 [Refactor] request body 수정
  src/components/book/SelectSeatComponent.vue
  src/stores/useBookingStore.js
Labels: 🩵 frontend, 💜 refactor

#12 [Refactor] 동적 취소 날짜 설정 및 전역 변수 의존성 제거
  src/components/book/SelectPriceComponent.vue
  src/stores/useBookingStore.js
Labels: 🩵 frontend, 💜 refactor

#15 [Feat] 페이지별 무한 스크롤 기능 추가 및 파비콘 설정 [#5, #13]
  public/favicon.ico
  public/favicon2.ico
  public/favicon3.ico
  public/index.html
  src/components/common/InfiniteScroll.vue
  src/components/main/CategoryComponent.vue
  src/components/main/MainPageComponent.vue
  src/components/main/SearchComponent.vue
  src/router/index.js
  src/stores/useProgramsStore.js
Labels: 💛 feature, 🩵 frontend
